### ISSUE TITLE
test_finds_small_list can fail if it generates first value <1001

### ISSUE THREAD

**Issue by Janiczek** [DRMacIver/minithesis#4]
Currently it's possible to generate a list that fails the test but can't be shrunk to `[1001]`: choices `[1, 100, 1, 901, 0]` translate to list `[100, 901]`. No shrinking will help here.

https://github.com/DRMacIver/minithesis/blob/9fa89b34c6fe914d9d76ef45182198cf30550351/test_minithesis.py#L24-L35

A solution could be to only generate values in the range [1001, 10000] instead of [0, 10000].

[Here's how this issue is fixed in `elm-minithesis`.](https://github.com/Janiczek/elm-minithesis/commit/0ab392544da0699be90588d28c4c2b5fc4b9234b)

**Comment by DRMacIver** [comment]
Hmm. Yeah.

I feel like that solution doesn't really test the same thing. Maybe the test should be changed to something like `assert not ls or max(ls) <= 1000`.

This is a problem with shrinker tests in general TBH - unless your shrinker is *really* good there will tend to be ways in which it gets stuck. Even Hypothesis won't always get this test right until https://github.com/HypothesisWorks/hypothesis/pull/2496 is merged.

**Comment by DRMacIver** [comment]
Solution: Make this test pass instead!

I've added a few more local shrink passes to the shrinker under a "Implement these for bragging rights" section. With these in place, this test will pass.

**Comment by Janiczek** [comment]
Having ported these shrinkers to elm-hypothesis, it found `[1,1,1,1000,0]` which corresponds to a value `[1,1000]`.

I'm having a hard time imagining how it could be shrunk to `[1,1001,0]` (value `[1001]`) (which is shorter so should be better) with the shrinkers available.

Does your "redistributing" shrinker perhaps try not just going from `[a, _, b]` to `[0, _, b+a]` but also in the other direction, `[b+a, _, 0]`? That would perhaps get it unstuck in combination with deleting some chunks later :thinking:

Do you see something I'm missing?

----

PS: Also it's unclear to me how to hack `minithesis.py` or `test_minithesis.py` to start with these choices and see what your shrinkers do. (It's possible my shrinkers have some bug / ommision that gets `elm-minithesis` stuck on the problematic run above, hence why I wanted to see what your shrinkers do and compare with my own.)

```python
def test_example_from_martin():
  def tf(tc):
    ...

  state = State(Random(0), tf, 100)
  tc = TC.for_choices(array('Q',[1,1,1,1000,0]))

  # ??? state.test_function(tc) - not quite, it seems it's missing the
  # `try...except` and marking failures as interesting that's in `run_test()`
```

**Comment by Janiczek** [comment]
Ah, I think I found it - the path to shrinking this should be
```
[1,1,1,1000,0]
[1,0,1,1001,0] -- by redistributing values in indices 1 and 3
[1,1001,0] -- by removing the chunk `[0,1]` starting at index `1`
```
So the fault is in my binary search - it doesn't try `f(low)` first. :tada:

EDIT: yup, after fixing that in https://github.com/Janiczek/elm-minithesis/commit/fa98208b2bf2a43baca7bcd1dad07ae30055e1c7 my shrinkers get that to `[1,1001,0]` successfully.

**Comment by DRMacIver** [comment]
> PS: Also it's unclear to me how to hack minithesis.py or test_minithesis.py to start with these choices and see what your shrinkers do

The easiest way to do this is probably to instantiate the state object explicitly, call `state.test_function(blah)` and then `state.shrink()`. It's not straightforward to do it with the tests themselves though.
